# Generated by Django 5.1.6 on 2025-04-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False)),
                ('battery_status', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('going_home', models.BooleanField(default=False)),
                ('motor_brake_released', models.BooleanField(default=False)),
                ('emergency_stop', models.BooleanField(default=False)),
                ('charging', models.BooleanField(default=True)),
                ('dockingStatus', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
