# Generated by Django 5.1.6 on 2025-04-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='charging',
            field=models.BooleanField(default=False),
        ),
    ]
