# Generated by Django 5.1.6 on 2025-04-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_robot_charging'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastClickedNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_id', models.IntegerField()),
                ('navigation_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
