# Generated by Django 5.1.6 on 2025-04-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_lastclickednavigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
