# Generated by Django 5.1.6 on 2025-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_basestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigations', models.JSONField(default=list)),
            ],
        ),
    ]
