# Generated by Django 5.1.6 on 2025-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fulltour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
