# Generated by Django 5.1.6 on 2025-04-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_poweron'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltour',
            name='tour_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulltour',
            name='tour_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
