# Generated by Django 5.1.6 on 2025-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_fulltour_tour_date_fulltour_tour_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebootStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
