# Generated by Django 5.1.6 on 2025-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
