# Generated by Django 5.1.6 on 2025-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_charge_sound_fulltour_full_tour_name_robot_stock_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='stock_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
