# Generated by Django 5.1.6 on 2025-05-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_charging_ipaddress_stock_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
