# Generated by Django 5.0.13 on 2025-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_navigationcancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='0.1', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='sound',
            name='value',
            field=models.CharField(default='60', max_length=151),
        ),
    ]
