# Generated by Django 5.0.13 on 2025-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_speed_alter_sound_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
