# Generated by Django 5.2 on 2025-05-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_refreshbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebootstatus',
            name='refresh',
            field=models.CharField(default='running'),
        ),
    ]
