# Generated by Django 5.2 on 2025-05-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rebootstatus_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebootstatus',
            name='refresh',
        ),
    ]
