# Generated by Django 5.2.1 on 2025-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_apicredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_id', models.IntegerField(unique=True)),
                ('scheduler_name', models.CharField(max_length=255)),
                ('scheduler_date', models.DateField()),
                ('scheduler_time', models.TimeField()),
                ('all_day', models.CharField(max_length=10)),
                ('modified', models.CharField(max_length=10)),
            ],
        ),
    ]
