# Generated by Django 5.2.1 on 2025-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='scheduler_date',
            field=models.DateTimeField(),
        ),
    ]
