# Generated by Django 5.2.1 on 2025-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_scheduler_scheduler_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
