# Generated by Django 5.2.1 on 2025-06-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_scheduler_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerConnectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_url', models.CharField(max_length=2048, unique=True)),
                ('customer_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
